import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import LineChart from "../Components/LineChart";
import PieChart from "../Components/PieChart";
import BarChart from "../Components/BarChart";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <LineChart />
        <PieChart />
        <BarChart />
      </main>
    </div>
  );
}
